LAB EST- FINAL PROJECT

DT PROJECT

CAR COLLECTIONS

In [23]:
import pandas as pd
df=pd.read_csv("/content/CARS DATA.csv")
df

,ID,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Price
0,44020629,-,VOLKSWAGEN,Golf,2012,Hatchback,No,Diesel,2.0 Turbo,0 km,4,Manual,Front,02-Mar,Left wheel,Grey,10,NaN
1,45784798,-,HYUNDAI,Sonata,2012,Sedan,Yes,Petrol,2.4,26000 km,4,Tiptronic,Front,04-May,Left wheel,Grey,10,NaN
2,45800257,-,NISSAN,Tiida,2005,Sedan,No,Petrol,1.5,168000 km,4,Automatic,Front,04-May,Right-hand drive,Sky blue,8,NaN
3,45797981,975,VOLVO,XC90,2012,Jeep,Yes,Petrol,3.2,143000 km,6,Automatic,4x4,04-May,Left wheel,Blue,12,NaN
4,45814303,-,OPEL,Astra,1993,Hatchback,No,Petrol,1.6,200000 km,4,Manual,Front,04-May,Left wheel,Black,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8240,44824410,1357,FIAT,Stilo,2004,Universal,No,Petrol,1.6,164000 km,4,Manual,Front,04-May,Left wheel,Blue,6,NaN
8241,45682346,-,BMW,528 F10,2012,Sedan,Yes,Petrol,2.8 Turbo,156000 km,4,Tiptronic,Front,04-May,Left wheel,Black,6,NaN
8242,45649860,1646,LEXUS,GX 460,2015,Jeep,Yes,Petrol,4.6,102907 km,8,Automatic,4x4,04-May,Left wheel,Black,0,NaN
8243,45809706,784,TOYOTA,Aqua,2017,Hatchback,Yes,Petrol,1.5,3000 km,4,Automatic,Front,04-May,Left wheel,Green,4,NaN
8244,45813163,448,HONDA,Insight,2012,Hatchback,Yes,Hybrid,1.3,321269 km,4,Automatic,Front,04-May,Left wheel,Red,12,NaN

In [24]:
# Drop some unwanted columns in DATASET

#syntax for drop any Row/Column
#df.drop("Name of row/column", inplace = True, axis = 0 or 1)   0 for row , 1 for column
df.drop("ID", inplace = True , axis=1)

In [25]:
z=['Levy','Cylinders','Doors']
for i in z:
   df.drop( i,inplace = True , axis = 1)

In [26]:
df

,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Gear box type,Drive wheels,Wheel,Color,Airbags,Price
0,VOLKSWAGEN,Golf,2012,Hatchback,No,Diesel,2.0 Turbo,0 km,Manual,Front,Left wheel,Grey,10,NaN
1,HYUNDAI,Sonata,2012,Sedan,Yes,Petrol,2.4,26000 km,Tiptronic,Front,Left wheel,Grey,10,NaN
2,NISSAN,Tiida,2005,Sedan,No,Petrol,1.5,168000 km,Automatic,Front,Right-hand drive,Sky blue,8,NaN
3,VOLVO,XC90,2012,Jeep,Yes,Petrol,3.2,143000 km,Automatic,4x4,Left wheel,Blue,12,NaN
4,OPEL,Astra,1993,Hatchback,No,Petrol,1.6,200000 km,Manual,Front,Left wheel,Black,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8240,FIAT,Stilo,2004,Universal,No,Petrol,1.6,164000 km,Manual,Front,Left wheel,Blue,6,NaN
8241,BMW,528 F10,2012,Sedan,Yes,Petrol,2.8 Turbo,156000 km,Tiptronic,Front,Left wheel,Black,6,NaN
8242,LEXUS,GX 460,2015,Jeep,Yes,Petrol,4.6,102907 km,Automatic,4x4,Left wheel,Black,0,NaN
8243,TOYOTA,Aqua,2017,Hatchback,Yes,Petrol,1.5,3000 km,Automatic,Front,Left wheel,Green,4,NaN
8244,HONDA,Insight,2012,Hatchback,Yes,Hybrid,1.3,321269 km,Automatic,Front,Left wheel,Red,12,NaN

In [27]:
en=str(input("enter engine type : "))
i=0
d_1=[]
while i<8244:
    if str(df.iloc[i,6])>=en:
        d_1.append(i)
        print(df.iloc[i])
        print("_____________________________________________________________________________________________")
        i+=1
    else:
        i+=1
print(d_1)

Streaming output truncated to the last 5000 lines.
Drive wheels              Rear
Wheel               Left wheel
Color                   Silver
Airbags                     10
Price                      NaN
Name: 7499, dtype: object
_____________________________________________________________________________________________
Manufacturer              JEEP
Model                 Cherokee
Prod. year                2006
Category                  Jeep
Leather interior           Yes
Fuel type               Diesel
Engine volume        2.8 Turbo
Mileage              263318 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                   Silver
Airbags                      2
Price                      NaN
Name: 7500, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                       E 240
Prod. year                   2000
Category                    Sedan
Leather interior               No
Fuel type                  Petrol
Engine volume                 2.4
Mileage                  21678 km
Gear box type              Manual
Drive wheels                 Rear
Wheel                  Left wheel
Color                      Silver
Airbags                         6
Price                         NaN
Name: 7502, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                       X5
Prod. year                2012
Category                  Jeep
Leather interior           Yes
Fuel type               Diesel
Engine volume                3
Mileage              229966 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                      0
Price                      NaN
Name: 7503, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model                   Malibu
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              159720 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 7507, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                       E 350
Prod. year                   2011
Category                    Sedan
Leather interior              Yes
Fuel type                  Diesel
Engine volume                 3.5
Mileage                 230696 km
Gear box type           Automatic
Drive wheels                  4x4
Wheel                  Left wheel
Color                       Black
Airbags                        12
Price                         NaN
Name: 7510, dtype: object
_____________________________________________________________________________________________
Manufacturer             LEXUS
Model                   GX 460
Prod. year                2010
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              4.6
Mileage              155821 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                      0
Price                      NaN
Name: 7515, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                       X5
Prod. year                2011
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume                3
Mileage                   0 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 7518, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                      114
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              4.4
Mileage              129683 km
Gear box type        Automatic
Drive wheels              Rear
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 7519, dtype: object
_____________________________________________________________________________________________
Manufacturer             LEXUS
Model                   ES 300
Prod. year                2010
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              157611 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                      4
Price                      NaN
Name: 7520, dtype: object
_____________________________________________________________________________________________
Manufacturer             LEXUS
Model                   GX 470
Prod. year                2010
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              4.6
Mileage              357246 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                     Grey
Airbags                      0
Price                      NaN
Name: 7521, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                      ML 350
Prod. year                   2012
Category                     Jeep
Leather interior              Yes
Fuel type                  Diesel
Engine volume                 3.5
Mileage                 245762 km
Gear box type           Automatic
Drive wheels                  4x4
Wheel                  Left wheel
Color                       Black
Airbags                        12
Price                         NaN
Name: 7523, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                       H1
Prod. year                2014
Category               Minivan
Leather interior           Yes
Fuel type               Diesel
Engine volume              2.5
Mileage              106200 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      4
Price                      NaN
Name: 7524, dtype: object
_____________________________________________________________________________________________
Manufacturer              AUDI
Model                       A6
Prod. year                2016
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume                3
Mileage              121762 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    White
Airbags                      0
Price                      NaN
Name: 7529, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                    S 500 67
Prod. year                   1999
Category                    Sedan
Leather interior              Yes
Fuel type                     CNG
Engine volume                 3.2
Mileage                   6789 km
Gear box type           Tiptronic
Drive wheels                 Rear
Wheel                  Left wheel
Color                        Blue
Airbags                        10
Price                         NaN
Name: 7531, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                       X5
Prod. year                2012
Category                  Jeep
Leather interior           Yes
Fuel type               Diesel
Engine volume                3
Mileage               70994 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                      0
Price                      NaN
Name: 7532, dtype: object
_____________________________________________________________________________________________
Manufacturer             MAZDA
Model                     CX-5
Prod. year                2014
Category                  Jeep
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage              153600 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                      Red
Airbags                     10
Price                      NaN
Name: 7533, dtype: object
_____________________________________________________________________________________________
Manufacturer              MITSUBISHI
Model                      Outlander
Prod. year                      2006
Category                        Jeep
Leather interior                  No
Fuel type                     Petrol
Engine volume                    2.4
Mileage                    136500 km
Gear box type              Tiptronic
Drive wheels                     4x4
Wheel               Right-hand drive
Color                         Silver
Airbags                            6
Price                            NaN
Name: 7535, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2011
Category                 Sedan
Leather interior            No
Fuel type               Hybrid
Engine volume              2.4
Mileage              203200 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      8
Price                      NaN
Name: 7537, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                  Transit
Prod. year                1996
Category              Microbus
Leather interior            No
Fuel type               Diesel
Engine volume              2.5
Mileage              123000 km
Gear box type           Manual
Drive wheels              Rear
Wheel               Left wheel
Color                    White
Airbags                      2
Price                      NaN
Name: 7540, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                    S 63 AMG
Prod. year                   2009
Category                    Sedan
Leather interior               No
Fuel type                  Petrol
Engine volume                 6.3
Mileage                 180000 km
Gear box type           Automatic
Drive wheels                 Rear
Wheel                  Left wheel
Color                        Grey
Airbags                         0
Price                         NaN
Name: 7542, dtype: object
_____________________________________________________________________________________________
Manufacturer             TOYOTA
Model               RAV 4 SPORT
Prod. year                 2012
Category                   Jeep
Leather interior             No
Fuel type                Petrol
Engine volume               2.5
Mileage               153000 km
Gear box type         Automatic
Drive wheels                4x4
Wheel                Left wheel
Color                     Black
Airbags                       6
Price                       NaN
Name: 7543, dtype: object
_____________________________________________________________________________________________
Manufacturer             LEXUS
Model                   RX 450
Prod. year                2013
Category                  Jeep
Leather interior           Yes
Fuel type               Hybrid
Engine volume              3.5
Mileage              138038 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 7546, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model               Highlander
Prod. year                2010
Category                 Sedan
Leather interior           Yes
Fuel type               Hybrid
Engine volume              3.3
Mileage              226198 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    Green
Airbags                     12
Price                      NaN
Name: 7547, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2019
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage                6000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 7552, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Hybrid
Engine volume              2.4
Mileage                   0 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                      0
Price                      NaN
Name: 7556, dtype: object
_____________________________________________________________________________________________
Manufacturer        LAND ROVER
Model                 Defender
Prod. year                1998
Category                  Jeep
Leather interior            No
Fuel type               Diesel
Engine volume        2.5 Turbo
Mileage              225000 km
Gear box type           Manual
Drive wheels               4x4
Wheel               Left wheel
Color                    White
Airbags                      0
Price                      NaN
Name: 7563, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                  Transit
Prod. year                1998
Category              Microbus
Leather interior            No
Fuel type               Diesel
Engine volume        2.5 Turbo
Mileage              111111 km
Gear box type           Manual
Drive wheels              Rear
Wheel               Left wheel
Color                    White
Airbags                      1
Price                      NaN
Name: 7564, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model                  Captiva
Prod. year                2013
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              222866 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 7570, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model               Highlander
Prod. year                2008
Category                  Jeep
Leather interior           Yes
Fuel type               Hybrid
Engine volume              3.3
Mileage              277405 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 7571, dtype: object
_____________________________________________________________________________________________
Manufacturer            NISSAN
Model                  Terrano
Prod. year                1999
Category                  Jeep
Leather interior            No
Fuel type                  CNG
Engine volume              2.4
Mileage               50000 km
Gear box type           Manual
Drive wheels               4x4
Wheel               Left wheel
Color                    Green
Airbags                      0
Price                      NaN
Name: 7572, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                       X5
Prod. year                2015
Category                  Jeep
Leather interior           Yes
Fuel type               Diesel
Engine volume                3
Mileage              196614 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                      0
Price                      NaN
Name: 7574, dtype: object
_____________________________________________________________________________________________
Manufacturer             LEXUS
Model                   RX 450
Prod. year                2010
Category                  Jeep
Leather interior           Yes
Fuel type               Hybrid
Engine volume              3.5
Mileage              315270 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 7579, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                       E 350
Prod. year                   2008
Category                    Sedan
Leather interior              Yes
Fuel type                  Diesel
Engine volume                 3.5
Mileage                 122874 km
Gear box type           Automatic
Drive wheels                 Rear
Wheel                  Left wheel
Color                       Black
Airbags                        12
Price                         NaN
Name: 7580, dtype: object
_____________________________________________________________________________________________
Manufacturer              JEEP
Model                 Wrangler
Prod. year                2011
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.8
Mileage               65000 km
Gear box type           Manual
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                      8
Price                      NaN
Name: 7582, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              138000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     10
Price                      NaN
Name: 7586, dtype: object

In [30]:
fu=str(input("enter fuel type : "))
d_2=[]
for t in d_1 :
  if str(df.iloc[t,5])==fu:
        d_2.append(t)
        print(df.iloc[t])
        print("_____________________________________________________________________________________________")

Streaming output truncated to the last 5000 lines.
Gear box type        Tiptronic
Drive wheels               4x4
Wheel               Left wheel
Color                   Silver
Airbags                      6
Price                      NaN
Name: 6705, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                 Explorer
Prod. year                2017
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage               52030 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      4
Price                      NaN
Name: 6710, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2016
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               38000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 6711, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                       E 350
Prod. year                   2007
Category                    Sedan
Leather interior              Yes
Fuel type                  Petrol
Engine volume                 3.5
Mileage                 165018 km
Gear box type           Tiptronic
Drive wheels                 Rear
Wheel                  Left wheel
Color                      Silver
Airbags                        12
Price                         NaN
Name: 6712, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                       E 350
Prod. year                   2014
Category                    Sedan
Leather interior              Yes
Fuel type                  Petrol
Engine volume                 5.5
Mileage                 101424 km
Gear box type           Automatic
Drive wheels                  4x4
Wheel                  Left wheel
Color                        Grey
Airbags                        12
Price                         NaN
Name: 6714, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                    530 M
Prod. year                2001
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume                3
Mileage              186900 km
Gear box type        Tiptronic
Drive wheels              Rear
Wheel               Left wheel
Color                   Golden
Airbags                      8
Price                      NaN
Name: 6736, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model                 Colorado
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.6
Mileage               79093 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 6737, dtype: object
_____________________________________________________________________________________________
Manufacturer               TOYOTA
Model                       Camry
Prod. year                   2011
Category                    Sedan
Leather interior               No
Fuel type                  Petrol
Engine volume                 2.5
Mileage                  11800 km
Gear box type           Tiptronic
Drive wheels                Front
Wheel                  Left wheel
Color               Carnelian red
Airbags                         8
Price                         NaN
Name: 6739, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                  Touareg
Prod. year                2004
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              4.2
Mileage              279000 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                     Blue
Airbags                     10
Price                      NaN
Name: 6742, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              134400 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     10
Price                      NaN
Name: 6746, dtype: object
_____________________________________________________________________________________________
Manufacturer             HONDA
Model                  Odyssey
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage                   0 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Pink
Airbags                     12
Price                      NaN
Name: 6747, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                     GLE 400
Prod. year                   2016
Category                     Jeep
Leather interior              Yes
Fuel type                  Petrol
Engine volume           3.0 Turbo
Mileage                  86000 km
Gear box type           Tiptronic
Drive wheels                  4x4
Wheel                  Left wheel
Color                       Black
Airbags                        12
Price                         NaN
Name: 6748, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                   Tundra
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              4.6
Mileage              190875 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 6749, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                      535
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume        3.0 Turbo
Mileage              115200 km
Gear box type        Tiptronic
Drive wheels              Rear
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 6751, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                 Explorer
Prod. year                2014
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage               90000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      4
Price                      NaN
Name: 6753, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              197600 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 6761, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2010
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage              256000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      0
Price                      NaN
Name: 6769, dtype: object
_____________________________________________________________________________________________
Manufacturer          DAIHATSU
Model                   Terios
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              5.7
Mileage              106853 km
Gear box type        Automatic
Drive wheels              Rear
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 6772, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                  Mustang
Prod. year                2017
Category                 Coupe
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.7
Mileage               97518 km
Gear box type        Automatic
Drive wheels              Rear
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 6776, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                      535
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume        3.0 Turbo
Mileage              150000 km
Gear box type        Tiptronic
Drive wheels              Rear
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 6779, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                   Fusion
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               71429 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                      Red
Airbags                     12
Price                      NaN
Name: 6781, dtype: object
_____________________________________________________________________________________________
Manufacturer          INFINITI
Model                      Q45
Prod. year                2003
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              4.5
Mileage              180000 km
Gear box type        Tiptronic
Drive wheels              Rear
Wheel               Left wheel
Color                     Blue
Airbags                      4
Price                      NaN
Name: 6789, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                   Tacoma
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume                4
Mileage              365810 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 6790, dtype: object
_____________________________________________________________________________________________
Manufacturer           PORSCHE
Model                  Cayenne
Prod. year                2014
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume        3.6 Turbo
Mileage               54123 km
Gear box type        Tiptronic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 6796, dtype: object
_____________________________________________________________________________________________
Manufacturer                  JEEP
Model               Wrangler sport
Prod. year                    2011
Category                      Jeep
Leather interior                No
Fuel type                   Petrol
Engine volume                  3.8
Mileage                  174444 km
Gear box type            Tiptronic
Drive wheels                   4x4
Wheel                   Left wheel
Color                        Black
Airbags                         10
Price                          NaN
Name: 6797, dtype: object
_____________________________________________________________________________________________
Manufacturer              JEEP
Model                  Compass
Prod. year                2015
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               83986 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      4
Price                      NaN
Name: 6798, dtype: object
_____________________________________________________________________________________________
Manufacturer              AUDI
Model                       Q7
Prod. year                2014
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume                3
Mileage              136605 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 6801, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                       G 320
Prod. year                   1998
Category                     Jeep
Leather interior              Yes
Fuel type                  Petrol
Engine volume                 3.2
Mileage                 170000 km
Gear box type           Automatic
Drive wheels                  4x4
Wheel                  Left wheel
Color                       Black
Airbags                         8
Price                         NaN
Name: 6805, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                   Tacoma
Prod. year                2013
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume                4
Mileage              239342 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 6810, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                 X5 Sport
Prod. year                2011
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume        3.0 Turbo
Mileage              170000 km
Gear box type        Tiptronic
Drive wheels               4x4
Wheel               Left wheel
Color                    Black
Airbags                      8
Price                      NaN
Name: 6814, dtype: object
_____________________________________________________________________________________________
Manufacturer          INFINITI
Model                     FX35
Prod. year                2008
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              157000 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 6819, dtype: object
_____________________________________________________________________________________________
Manufacturer        MERCEDES-BENZ
Model                       E 500
Prod. year                   2003
Category                    Sedan
Leather interior              Yes
Fuel type                  Petrol
Engine volume                   5
Mileage                 275545 km
Gear box type           Tiptronic
Drive wheels                 Rear
Wheel                  Left wheel
Color                      Golden
Airbags                         8
Price                         NaN
Name: 6824, dtype: object
_____________________________________________________________________________________________
Manufacturer               BMW
Model                      328
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume                3
Mileage              112000 km
Gear box type        Automatic
Drive wheels              Rear
Wheel               Left wheel
Color                   Silver
Airbags                      6
Price                      NaN
Name: 6827, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                   Fusion
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              278248 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 6830, dtype: object
_____________________________________________________________________________________________
Manufacturer               NISSAN
Model               Quest LIMITED
Prod. year                   2014
Category                  Minivan
Leather interior              Yes
Fuel type                  Petrol
Engine volume                 3.5
Mileage                  55000 km
Gear box type           Automatic
Drive wheels                Front
Wheel                  Left wheel
Color                       White
Airbags                        12
Price                         NaN
Name: 6832, dtype: object
_____________________________________________________________________________________________
Manufacturer             MAZDA
Model                     CX-9
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.7
Mileage               55858 km
Gear box type        Automatic
Drive wheels               4x4
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN

In [31]:
dw=str(input("enter drive wheel type : "))
d_3=[]
for t in d_2 :
    if str(df.iloc[t,9])==dw:
        d_3.append(t)
        print(df.iloc[t])
        print("_____________________________________________________________________________________________")

Streaming output truncated to the last 5000 lines.
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      0
Price                      NaN
Name: 4166, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               80000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     16
Price                      NaN
Name: 4178, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model               Malibu LTZ
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              135000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 4196, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model                   Impala
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               79932 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      4
Price                      NaN
Name: 4227, dtype: object
_____________________________________________________________________________________________
Manufacturer               HYUNDAI
Model               Sonata limited
Prod. year                    2011
Category                     Sedan
Leather interior               Yes
Fuel type                   Petrol
Engine volume                  2.4
Mileage                  126000 km
Gear box type            Tiptronic
Drive wheels                 Front
Wheel                   Left wheel
Color                       Silver
Airbags                         12
Price                          NaN
Name: 4236, dtype: object
_____________________________________________________________________________________________
Manufacturer             BUICK
Model                  Enclave
Prod. year                2020
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.6
Mileage               29717 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 4237, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                   Taurus
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              195637 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 4239, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              121952 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 4264, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               83000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 4279, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                  Genesis
Prod. year                2011
Category                 Coupe
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.8
Mileage              114021 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      4
Price                      NaN
Name: 4289, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2016
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage                   0 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      0
Price                      NaN
Name: 4299, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage              167000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                      8
Price                      NaN
Name: 4310, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               72000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      8
Price                      NaN
Name: 4316, dtype: object
_____________________________________________________________________________________________
Manufacturer             ACURA
Model                      TLX
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               83099 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 4318, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Tucson
Prod. year                2013
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               44371 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 4325, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage                   0 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 4336, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                   Optima
Prod. year                2016
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage               46400 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 4343, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                  Elantra
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              130000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      6
Price                      NaN
Name: 4354, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                   Optima
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               60000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      8
Price                      NaN
Name: 4359, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              150000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                      6
Price                      NaN
Name: 4373, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                    Jetta
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              180000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      6
Price                      NaN
Name: 4374, dtype: object
_____________________________________________________________________________________________
Manufacturer              AUDI
Model                      100
Prod. year                1995
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.8
Mileage              270472 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                      2
Price                      NaN
Name: 4381, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                     F150
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              206000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      4
Price                      NaN
Name: 4393, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              147904 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 4436, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2018
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume        2.5 Turbo
Mileage                9000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      8
Price                      NaN
Name: 4449, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2010
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage              137000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Brown
Airbags                      8
Price                      NaN
Name: 4478, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2010
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              285621 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 4497, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                   Optima
Prod. year                2009
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.3
Mileage               78114 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      4
Price                      NaN
Name: 4503, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2011
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage              172800 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 4511, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                 Camry SE
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              144000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                      9
Price                      NaN
Name: 4517, dtype: object
_____________________________________________________________________________________________
Manufacturer              JEEP
Model                  Compass
Prod. year                2013
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               90757 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      4
Price                      NaN
Name: 4535, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              132165 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 4569, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              215621 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                      Red
Airbags                     12
Price                      NaN
Name: 4572, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                  Sorento
Prod. year                2014
Category                  Jeep
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              112883 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 4593, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              122950 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 4607, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               80000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 4628, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol

In [34]:
co=str(input("enter category : "))
d_4=[]
print("\nTHESE are the cars witch fit you most : \n")
for t in d_3 :
    if str(df.iloc[t,3])==co:
        d_4.append(t)
        print(df.iloc[t])
        print("_____________________________________________________________________________________________")

Streaming output truncated to the last 5000 lines.
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      8
Price                      NaN
Name: 2962, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                   Optima
Prod. year                2016
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage              131200 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      8
Price                      NaN
Name: 2963, dtype: object
_____________________________________________________________________________________________
Manufacturer                CHRYSLER
Model               Town and Country
Prod. year                      2014
Category                       Sedan
Leather interior                 Yes
Fuel type                     Petrol
Engine volume                    3.6
Mileage                    243907 km
Gear box type              Automatic
Drive wheels                   Front
Wheel                     Left wheel
Color                         Silver
Airbags                           12
Price                            NaN
Name: 2965, dtype: object
_____________________________________________________________________________________________
Manufacturer             TOYOTA
Model               Camry sport
Prod. year                 2016
Category                  Sedan
Leather interior            Yes
Fuel type                Petrol
Engine volume               2.5
Mileage                53900 km
Gear box type         Tiptronic
Drive wheels              Front
Wheel                Left wheel
Color                     Black
Airbags                      12
Price                       NaN
Name: 2974, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              168000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      4
Price                      NaN
Name: 2975, dtype: object
_____________________________________________________________________________________________
Manufacturer            NISSAN
Model                   Altima
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              124282 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 2999, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                    Jetta
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              184821 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 3003, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                Passat se
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               71000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      6
Price                      NaN
Name: 3017, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2019
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               29419 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 3026, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                   Sienna
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              248253 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 3053, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                   Avalon
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage               93638 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      0
Price                      NaN
Name: 3093, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2012
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage                1000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                      8
Price                      NaN
Name: 3120, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                   Optima
Prod. year                2016
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage               36800 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     10
Price                      NaN
Name: 3145, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              164616 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 3149, dtype: object
_____________________________________________________________________________________________
Manufacturer             HONDA
Model                   Accord
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              237309 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Purple
Airbags                     12
Price                      NaN
Name: 3152, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              190124 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      6
Price                      NaN
Name: 3181, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                   Passat
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               75307 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 3206, dtype: object
_____________________________________________________________________________________________
Manufacturer             DODGE
Model                  Avenger
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.6
Mileage              253019 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 3208, dtype: object
_____________________________________________________________________________________________
Manufacturer             BUICK
Model                  Century
Prod. year                2002
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.1
Mileage              164826 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 3212, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2018
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               45371 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 3225, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                   Passat
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              148000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     10
Price                      NaN
Name: 3233, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              120000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 3242, dtype: object
_____________________________________________________________________________________________
Manufacturer             MAZDA
Model                      616
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               67309 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                      Red
Airbags                     12
Price                      NaN
Name: 3244, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2018
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               62345 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 3260, dtype: object
_____________________________________________________________________________________________
Manufacturer            NISSAN
Model                   Altima
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage                   0 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 3291, dtype: object
_____________________________________________________________________________________________
Manufacturer             MAZDA
Model                     1300
Prod. year                2019
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage                   0 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 3307, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage              166400 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      0
Price                      NaN
Name: 3338, dtype: object
_____________________________________________________________________________________________
Manufacturer             HONDA
Model                    Civic
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               74309 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                      Red
Airbags                      4
Price                      NaN
Name: 3358, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               86000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 3377, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2010
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              206245 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 3378, dtype: object
_____________________________________________________________________________________________
Manufacturer             ACURA
Model                       TL
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              187806 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 3379, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               53310 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 3385, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                    Jetta
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               68000 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 3439, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                   Passat
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              173280 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      8
Price                      NaN
Name: 3449, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              123200 km
Gear box type        Tiptronic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      4
Price                      NaN
Name: 3502, dtype: object
_____________________________________________________________________________________________
Manufacturer                CHRYSLER
Model               Town and Country
Prod. year                      2012
Category                       Sedan
Leather interior                 Yes
Fuel type                     Petrol
Engine volume                    3.6
Mileage                     80693 km
Gear box type              Automatic
Drive wheels                   Front
Wheel                     Left wheel
Color                            Red
Airbags                           12
Price                            NaN
Name: 3560, dtype: object
_____________________________________________________________________________________________
Manufacturer        VOLKSWAGEN
Model                Jetta SEL

In [35]:
co= input("Gear box type(Automatic/Tiptronic/Manual/Variator)  : ")
d_5=[]
print("\nTHESE are the cars witch fit you most : \n")
for t in d_4 :
    if str(df.iloc[t,8])==co:
        d_5.append(t)
        print(df.iloc[t])
        print("_____________________________________________________________________________________________")

print(d_5)

Gear box type(Automatic/Tiptronic/Manual/Variator)  : Automatic

THESE are the cars witch fit you most :

Manufacturer            TOYOTA
Model                    Camry
Prod. year                2010
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               74160 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 125, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2013
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage              136448 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                      0
Price                      NaN
Name: 128, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2019
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               39198 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 135, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model               Highlander
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              285186 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 157, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2016
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              135546 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 188, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2019
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               21502 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 202, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              169387 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 259, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                   Optima
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              169840 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 260, dtype: object
_____________________________________________________________________________________________
Manufacturer               GMC
Model                   Sierra
Prod. year                2015
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              5.3
Mileage              126682 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 284, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2017
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage               41280 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                      Red
Airbags                      6
Price                      NaN
Name: 419, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2017
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage               65000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 435, dtype: object
_____________________________________________________________________________________________
Manufacturer               KIA
Model                Optima lx
Prod. year                2016
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage               92000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      8
Price                      NaN
Name: 457, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model                 Colorado
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.6
Mileage               79093 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 480, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               87510 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                      0
Price                      NaN
Name: 489, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              238533 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 497, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                   Fusion
Prod. year                2013
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage              175000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 526, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model                   Impala
Prod. year                2016
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              100565 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      4
Price                      NaN
Name: 553, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              127700 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 581, dtype: object
_____________________________________________________________________________________________
Manufacturer             LEXUS
Model                   ES 300
Prod. year                2010
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage              168920 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                      4
Price                      NaN
Name: 628, dtype: object
_____________________________________________________________________________________________
Manufacturer             TOYOTA
Model               Camry sport
Prod. year                 2013
Category                  Sedan
Leather interior            Yes
Fuel type                Petrol
Engine volume               2.5
Mileage                82000 km
Gear box type         Automatic
Drive wheels              Front
Wheel                Left wheel
Color                     Black
Airbags                      12
Price                       NaN
Name: 635, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2020
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               14960 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                     12
Price                      NaN
Name: 639, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                 Grandeur
Prod. year                2013
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume                3
Mileage               55171 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    Black
Airbags                      4
Price                      NaN
Name: 641, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2016
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage               68941 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 655, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                 Explorer
Prod. year                2018
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage               79517 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                      Red
Airbags                     12
Price                      NaN
Name: 664, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                   Fusion
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              277810 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                   Silver
Airbags                     12
Price                      NaN
Name: 680, dtype: object
_____________________________________________________________________________________________
Manufacturer         CHEVROLET
Model                   Impala
Prod. year                2014
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.6
Mileage                   0 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 697, dtype: object
_____________________________________________________________________________________________
Manufacturer            NISSAN
Model                   Altima
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              498435 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 715, dtype: object
_____________________________________________________________________________________________
Manufacturer             MAZDA
Model                      616
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              280638 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Grey
Airbags                     12
Price                      NaN
Name: 763, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2012
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage              240602 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     12
Price                      NaN
Name: 792, dtype: object
_____________________________________________________________________________________________
Manufacturer            TOYOTA
Model                    Camry
Prod. year                2014
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.5
Mileage               98886 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      0
Price                      NaN
Name: 849, dtype: object
_____________________________________________________________________________________________
Manufacturer              FORD
Model                   Fusion
Prod. year                2016
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.5
Mileage               79000 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                     Blue
Airbags                     10
Price                      NaN
Name: 856, dtype: object
_____________________________________________________________________________________________
Manufacturer           HYUNDAI
Model                   Sonata
Prod. year                2011
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              2.4
Mileage              192229 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 858, dtype: object
_____________________________________________________________________________________________
Manufacturer                CHRYSLER
Model               Town and Country
Prod. year                      2014
Category                       Sedan
Leather interior                 Yes
Fuel type                     Petrol
Engine volume                    3.6
Mileage                    131218 km
Gear box type              Automatic
Drive wheels                   Front
Wheel                     Left wheel
Color                           Grey
Airbags                           12
Price                            NaN
Name: 864, dtype: object
_____________________________________________________________________________________________
Manufacturer            NISSAN
Model                   Murano
Prod. year                2017
Category                 Sedan
Leather interior           Yes
Fuel type               Petrol
Engine volume              3.5
Mileage               10834 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                     12
Price                      NaN
Name: 870, dtype: object
_____________________________________________________________________________________________
Manufacturer          CHRYSLER
Model                      200
Prod. year                2015
Category                 Sedan
Leather interior            No
Fuel type               Petrol
Engine volume              2.4
Mileage              108800 km
Gear box type        Automatic
Drive wheels             Front
Wheel               Left wheel
Color                    White
Airbags                      8
Price                      NaN
Name: 873, dtype: object
_____________________________________________________________________________________________
Manufacturer           MERCEDES-BENZ
Model                          E 320
Prod. year                      2003
Category                       Sedan
Leather interior                 Yes
Fuel type                     Petrol
Engine volume                    3.2
Mileage                    160000 km
Gear box type              Automatic
Drive wheels                   Front
Wheel               Right-hand drive